import { Inter } from "next/font/google";
import "./globals.css";
import AllProvider from "@/components/AllProvider/AllProvider";
import AuthProvider from "@/AuthProvider/AuthProvider";
import ReduxProvider from "@/components/reduxprovider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BPI || Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AllProvider>{children}</AllProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
