import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/AuthProvider/AuthProvider";
import ReduxProvider from "@/components/reduxprovider/ReduxProvider";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BPI || Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader></NextTopLoader>
        <AuthProvider>
          <ReduxProvider>
            <div>{children}</div>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
