export const products = [
  {
    id: "1",
    name: "Book1",
    title: "The Art of Programming",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/29.jpg",
    image2: "https://example.com/book1_image2.jpg",
    image3: null,
    price: 29.99,
    category: "Programming",
    writer_name: "John Coder",
    quantity: 100,
    description: "A comprehensive guide to programming.",
    department: "Computer Science",
    createdAt: "2024-02-07T12:00:00Z",
    comment: [
      {
        commentId: "101",
        text: "Great book! Highly recommended.",
        createdAt: "2024-02-08T08:30:00Z",
      },
      {
        commentId: "102",
        text: "I learned a lot from this book.",
        createdAt: "2024-02-10T10:15:00Z",
      },
    ],
  },
  {
    id: "1",
    name: "wp-content",
    title: "The Art of Programming",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/16.jpg",
    image2: "https://example.com/book1_image2.jpg",
    image3: null,
    price: 29.99,
    category: "Programming",
    writer_name: "John Coder",
    quantity: 100,
    description: "A comprehensive guide to programming.",
    department: "Computer Science",
    createdAt: "2024-02-07T12:00:00Z",
    comment: [
      {
        commentId: "101",
        text: "Great book! Highly recommended.",
        createdAt: "2024-02-08T08:30:00Z",
      },
      {
        commentId: "102",
        text: "I learned a lot from this book.",
        createdAt: "2024-02-10T10:15:00Z",
      },
    ],
  },
  {
    id: "2",
    name: "Book2",
    title: "The Science of Data",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/32.jpg",
    image2: null,
    image3: null,
    price: null,
    category: "Data Science",
    writer_name: "Jane DataScientist",
    quantity: 50,
    description: "Exploring the world of data science.",
    department: "Statistics",
    createdAt: "2024-02-07T14:30:00Z",
    comment: [],
  },
  {
    id: "1",
    name: "UniqueCodeBook1",
    title: "The Art of Programming",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/27.jpg",
    image2: "https://example.com/book1_image2.jpg",
    image3: null,
    price: 29.99,
    category: "Programming",
    writer_name: "John Coder",
    quantity: 100,
    description: "A comprehensive guide to programming.",
    department: "Computer Science",
    createdAt: "2024-02-07T12:00:00Z",
    comment: [
      {
        commentId: "101",
        text: "Great book! Highly recommended.",
        createdAt: "2024-02-08T08:30:00Z",
      },
      {
        commentId: "102",
        text: "I learned a lot from this book.",
        createdAt: "2024-02-10T10:15:00Z",
      },
    ],
  },
  {
    id: "2",
    name: "UniqueCodeBook2",
    title: "The Science of Data",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/28.jpg",
    image2: null,
    image3: null,
    price: null,
    category: "Data Science",
    writer_name: "Jane DataScientist",
    quantity: 50,
    description: "Exploring the world of data science.",
    department: "Statistics",
    createdAt: "2024-02-07T14:30:00Z",
    comment: [],
  },
  {
    id: "3",
    name: "UniqueCodeBook3",
    title: "The Mystery Novel",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/30.jpg",
    image2: "https://example.com/book3_image2.jpg",
    image3: "https://example.com/book3_image3.jpg",
    price: 19.99,
    category: "Mystery",
    writer_name: "Samantha Sleuth",
    quantity: 75,
    description: "A gripping mystery novel that keeps you on the edge.",
    department: "Literature",
    createdAt: "2024-02-08T09:45:00Z",
    comment: [
      {
        commentId: "103",
        text: "Couldn't put it down! Amazing plot twists.",
        createdAt: "2024-02-09T11:20:00Z",
      },
      {
        commentId: "104",
        text: "Perfect for mystery enthusiasts.",
        createdAt: "2024-02-12T14:10:00Z",
      },
    ],
  },
  {
    id: "4",
    name: "UniqueCodeBook4",
    title: "The Coding Almanac",
    image1:
      "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/02/31.jpg",
    image2: "https://example.com/book4_image2.jpg",
    image3: null,
    price: 39.99,
    category: "Programming",
    writer_name: "CodeMaster",
    quantity: 50,
    description:
      "A comprehensive reference for coding practices and algorithms.",
    department: "Computer Science",
    createdAt: "2024-02-09T13:15:00Z",
    comment: [
      {
        commentId: "105",
        text: "Essential for every programmer's library.",
        createdAt: "2024-02-10T15:45:00Z",
      },
      {
        commentId: "106",
        text: "Invaluable resource for coding interviews.",
        createdAt: "2024-02-13T09:30:00Z",
      },
    ],
  },
];
